### ISSUE TITLE
RegioTV not recognized in the IPTV group manager

### ISSUE THREAD

**Issue by pl0ng** [add-ons/plugin.video.regiotv#16]
Running latest releases on Kodi 18.7, RegioTV is not recognized in the IPTV group manager settings.
Addons VRTNu, VTMGo, 4-5-6 are recognized succesfully.

**Comment by dagwieers** [comment]
If you use the master branch, it should work fine. There has not been a release with IPTV Manager support because the add-on lacks an icon, so ww can not make new releases until we have an icon.
