### ISSUE TITLE
ATV no longer functioning due to change of link

### ISSUE THREAD

**Issue by pdb01** [add-ons/plugin.video.regiotv#43]
Hi all,

I've been enjoying this - and other add-ons - greatly. Thanks for the commitment!

However, ATV has teamed up with GVA and hence the link has changed recently, therefore ATV is no longer working within the RegioTV add-on.
The live stream now directs to https://player.agnoplay.com/embed/gvaatv-live 

Can this be updated, or anoher workaround to see this within Kodi?

thanks :-)

**Comment by peno64** [comment]
I updated the url and created a pool request but  the developer had to approve it.

**Comment by peno64** [comment]
Fixed
