### ISSUE TITLE
Focus news not the same as WTV -> different channels

### ISSUE THREAD

**Issue by heinreyn** [add-ons/plugin.video.regiotv#46]
It might seem as Focus and WTV are one and the same stream, there is in fact a difference in news broadcasts. Focus shows news from the north as WTV shows news from the south of WVL. The news program is different and thus the channels are not the same.
On the website one can find the 2 streams on the same page: http://www.wtv.be/live

Can you please add WTV again with the correct stream?

Before Kodi version 20, I wasn't able to play the stream without glitches, so it is the first time I can watch the channel and noticed the stream is Focus and not WTV.

**Comment by peno64** [comment]
Fixed in release 0.1.6
